# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-07-03 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171209_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='branch',
            name='district',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='branch',
            name='ifsc',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='state',
            field=models.CharField(max_length=500),
        ),
    ]
